# Generated by Django 5.1.1 on 2024-10-14 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_Users', '0004_remove_usuario_estado_alter_usuario_is_superuser'),
        ('pedidos', '0002_alter_pedido_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('multimedia', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('moderado', 'Moderado'), ('eliminado', 'Eliminado')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='model_Users.usuario')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='pedidos.pedido')),
            ],
        ),
    ]
