# Generated by Django 5.1.1 on 2024-10-14 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caninos', '0001_initial'),
        ('pedidos', '0002_alter_pedido_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCanino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caninos.canino')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caninos', to='pedidos.pedido')),
            ],
            options={
                'unique_together': {('pedido', 'canino')},
            },
        ),
    ]
