# Generated by Django 5.1.1 on 2024-10-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_Users', '0003_delete_user_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
