# Generated by Django 5.1.1 on 2024-10-14 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(choices=[('procesado', 'Procesado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], max_length=20)),
                ('metodo_pago', models.CharField(max_length=255)),
                ('comprobante_pago', models.TextField(blank=True, null=True)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('direccion_facturacion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='model_Users.user')),
            ],
        ),
    ]
